#!/usr/bin/env python3
"""Stamp the Glass build version into core/glass_version.gen.h.

Run by .github/workflows/glass-build.yml before scons so the editor binary knows
its own release tag and the Project Manager auto-update check can tell whether a
newer Glass release exists.

The tag comes from (in order): argv[1], $GLASS_VERSION, $GITHUB_REF_NAME.
If none are set (a plain local build), nothing is written and the engine falls
back to the dev sentinel in core/glass_version.h.
"""

import os
import sys

GEN_PATH = os.path.join("core", "glass_version.gen.h")


def resolve_tag() -> str:
    if len(sys.argv) > 1 and sys.argv[1].strip():
        return sys.argv[1].strip()
    for env_key in ("GLASS_VERSION", "GITHUB_REF_NAME"):
        val = os.environ.get(env_key, "").strip()
        if val:
            return val
    return ""


def main() -> int:
    tag = resolve_tag()
    if not tag:
        print("glass_stamp_version: no tag (GLASS_VERSION / GITHUB_REF_NAME / argv); leaving dev sentinel.")
        return 0

    # Guard against quote injection into the generated string literal.
    safe_tag = tag.replace("\\", "").replace('"', "")
    contents = (
        "// Generated by misc/scripts/glass_stamp_version.py — do not edit, do not commit.\n"
        "#pragma once\n"
        "#ifndef GLASS_VERSION_TAG\n"
        f'#define GLASS_VERSION_TAG "{safe_tag}"\n'
        "#endif\n"
    )
    with open(GEN_PATH, "w", encoding="utf-8") as f:
        f.write(contents)
    print(f"glass_stamp_version: stamped {GEN_PATH} with GLASS_VERSION_TAG=\"{safe_tag}\"")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
